<?php

// ACF
if(function_exists('acf_add_local_field_group')) {

	// Theme Options - General
	acf_add_local_field_group(array(
		'key' => 'group_5ad5104f810e6',
		'title' => 'General Settings',
		'fields' => array(
			array(
				'key' => 'field_5ad510b81a473',
				'label' => '',
				'name' => 'general_settings',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5ad510cc1a474',
						'label' => 'Smooth Scrolling',
						'name' => 'smooth_scrolling',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ad5126d05f98',
						'label' => 'Back To Top Button',
						'name' => 'back_to_top_button',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ad512a105f9a',
						'label' => 'XMLRPC Option',
						'name' => 'xmlrpc_option',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ad8a70500b79',
						'label' => 'Comments Form',
						'name' => 'comments_form',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ae340cea8571',
						'label' => 'Development Mode',
						'name' => 'development_mode',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => 'Disable caching for CSS and JavaScript.',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ae340cea8572',
						'label' => 'Parent Theme Styles',
						'name' => 'parent_css',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => 'Disable SME Parent CSS for full Child CSS control.',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ae3476491f9b',
						'label' => 'Cache Version Override',
						'name' => 'cache_version_override',
						'type' => 'text',
						'instructions' => 'Manual cache version override for style.css and common.js',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_6266b89b6ce8s',
		'title' => 'Analytics and Scripts',
		'fields' => array(
			array(
				'key' => 'field_6266ba9ca6d2s',
				'label' => '',
				'name' => 'site_scripts',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5ae3476491ga4',
						'label' => 'Google Analytics 4',
						'name' => 'site_ga_id',
						'type' => 'text',
						'instructions' => 'Global site tag will be inserted into the <head> tag. Enter GA4 ID: G-#',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
                    array(
						'key' => 'field_5ad519af4z420',
						'label' => 'GTM (Google Tag Manager)',
						'name' => 'google_tag_manager',
						'type' => 'text',
						'instructions' => 'Google Tag Manager code will be inserted into the &lt;head&gt; and &lt;body&gt;.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ae3476491f9h',
						'label' => 'Scripts in Header',
						'name' => 'scripts_in_header',
						'type' => 'textarea',
						'instructions' => 'Scripts will be inserted before the &#x3C;/head&#x3E; tag.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_5ae3476491f9a',
						'label' => 'Scripts in Footer',
						'name' => 'scripts_in_footer',
						'type' => 'textarea',
						'instructions' => 'Scripts will be inserted before the &#x3C;/body&#x3E; tag.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
	
	// Theme Options - Header
	acf_add_local_field_group(array(
		'key' => 'group_5ad5144dc32ae',
		'title' => 'Header Settings',
		'fields' => array(
			array(
				'key' => 'field_5ad5144dc90c8',
				'label' => '',
				'name' => 'header_settings',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5ad5144dcb754',
						'label' => 'Sticky Header',
						'name' => 'sticky_header',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
                    array(
						'key' => 'field_5ad5144dcb7fw',
						'label' => 'Header Width',
						'name' => 'header_width',
						'type' => 'radio',
						'instructions' => 'Contained - 12col center aligned. Full width - 2 rows full width nav.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'container-lg' => 'Contained',
							'container-fluid' => 'Full Width',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'container-lg',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5f231a4efa04a',
						'label' => 'Mobile Menu Type',
						'name' => 'mobile_menu_type',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'mm-inline' => 'Inline',
							'mm-overlay' => 'Overlay',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5ad753d79738f',
						'label' => 'Search Options',
						'name' => 'search_options',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5ade17db83f71',
								'label' => 'Display',
								'name' => 'display',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'hidden' => 'Hidden',
									'global' => 'Global Menu',
									'main' => 'Main Menu',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
								'return_format' => 'value',
							),
							array(
								'key' => 'field_5ade1f3812b48',
								'label' => 'Type',
								'name' => 'type',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'icon' => 'Search Icon',
									'input' => 'Search Input Field',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
								'return_format' => 'value',
							),
						),
					),
					array(
						'key' => 'field_5ad5149cff4a9',
						'label' => 'Logo Upload',
						'name' => 'logo_upload',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5f08a1f7e3696',
						'label' => 'Secondary Logo Upload',
						'name' => 'logo2_upload',
						'type' => 'image',
						'instructions' => 'Optional - Only appears if your theme supports it.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5ad51e05b067b',
						'label' => 'Page Default Banner Upload',
						'name' => 'default_banner_upload',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 2,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	// Theme Options - Footer
	acf_add_local_field_group(array(
		'key' => 'group_5ad518189015a',
		'title' => 'Footer Settings',
		'fields' => array(
			array(
				'key' => 'field_5ad5181895d24',
				'label' => '',
				'name' => 'footer_settings',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5ad51818988ad',
						'label' => 'Super Footer',
						'name' => 'super_footer',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ad518db46567',
						'label' => 'Super Footer Columns',
						'name' => 'super_footer_columns',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ad51818988ad',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5adf4de825059',
								'label' => 'Columns',
								'name' => 'columns',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									1 => '1',
									2 => '2',
									3 => '3',
									4 => '4',
									5 => '5',
									6 => '6',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
								'return_format' => 'value',
							),
							array(
								'key' => 'field_5adf51dae2b7e',
								'label' => 'Column 1',
								'name' => 'column_1',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'table',
								'sub_fields' => array(
									array(
										'key' => 'field_5adf5345e2b80',
										'label' => 'Options',
										'name' => 'options',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'menu' => 'Menu',
											'content' => 'Content',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5adf536be2b81',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf5345e2b80',
													'operator' => '==',
													'value' => 'content',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5adf6b4e3935c',
										'label' => 'Menu Location',
										'name' => 'menu',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf5345e2b80',
													'operator' => '==',
													'value' => 'menu',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'sfooter-menu-1' => 'Super Footer Menu 1',
											'sfooter-menu-2' => 'Super Footer Menu 2',
											'sfooter-menu-3' => 'Super Footer Menu 3',
											'sfooter-menu-4' => 'Super Footer Menu 4',
											'sfooter-menu-5' => 'Super Footer Menu 5',
											'sfooter-menu-6' => 'Super Footer Menu 6',
										),
										'default_value' => array(
											0 => 'sfooter-menu-1',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
								),
							),
							array(
								'key' => 'field_5adf6f9ba600c',
								'label' => 'Column 2',
								'name' => 'column_2',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '2',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '3',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '4',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '5',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '6',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'table',
								'sub_fields' => array(
									array(
										'key' => 'field_5adf6f9ca600d',
										'label' => 'Options',
										'name' => 'options',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'menu' => 'Menu',
											'content' => 'Content',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5adf6f9ca600e',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf6f9ca600d',
													'operator' => '==',
													'value' => 'content',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5adf6f9ca600f',
										'label' => 'Menu Location',
										'name' => 'menu',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf6f9ca600d',
													'operator' => '==',
													'value' => 'menu',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'sfooter-menu-1' => 'Super Footer Menu 1',
											'sfooter-menu-2' => 'Super Footer Menu 2',
											'sfooter-menu-3' => 'Super Footer Menu 3',
											'sfooter-menu-4' => 'Super Footer Menu 4',
											'sfooter-menu-5' => 'Super Footer Menu 5',
											'sfooter-menu-6' => 'Super Footer Menu 6',
										),
										'default_value' => array(
											0 => 'sfooter-menu-2',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
								),
							),
							array(
								'key' => 'field_5adf719034104',
								'label' => 'Column 3',
								'name' => 'column_3',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '3',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '4',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '5',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '6',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'table',
								'sub_fields' => array(
									array(
										'key' => 'field_5adf719034105',
										'label' => 'Options',
										'name' => 'options',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'menu' => 'Menu',
											'content' => 'Content',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5adf719034106',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf719034105',
													'operator' => '==',
													'value' => 'content',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5adf719034107',
										'label' => 'Menu Location',
										'name' => 'menu',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf719034105',
													'operator' => '==',
													'value' => 'menu',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'sfooter-menu-1' => 'Super Footer Menu 1',
											'sfooter-menu-2' => 'Super Footer Menu 2',
											'sfooter-menu-3' => 'Super Footer Menu 3',
											'sfooter-menu-4' => 'Super Footer Menu 4',
											'sfooter-menu-5' => 'Super Footer Menu 5',
											'sfooter-menu-6' => 'Super Footer Menu 6',
										),
										'default_value' => array(
											0 => 'sfooter-menu-3',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
								),
							),
							array(
								'key' => 'field_5adf72207188c',
								'label' => 'Column 4',
								'name' => 'column_4',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '4',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '5',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '6',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'table',
								'sub_fields' => array(
									array(
										'key' => 'field_5adf72207188d',
										'label' => 'Options',
										'name' => 'options',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'menu' => 'Menu',
											'content' => 'Content',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5adf72207188e',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf72207188d',
													'operator' => '==',
													'value' => 'content',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5adf72207188f',
										'label' => 'Menu Location',
										'name' => 'menu',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf72207188d',
													'operator' => '==',
													'value' => 'menu',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'sfooter-menu-1' => 'Super Footer Menu 1',
											'sfooter-menu-2' => 'Super Footer Menu 2',
											'sfooter-menu-3' => 'Super Footer Menu 3',
											'sfooter-menu-4' => 'Super Footer Menu 4',
											'sfooter-menu-5' => 'Super Footer Menu 5',
											'sfooter-menu-6' => 'Super Footer Menu 6',
										),
										'default_value' => array(
											0 => 'sfooter-menu-4',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
								),
							),
							array(
								'key' => 'field_5adf727d1f5e0',
								'label' => 'Column 5',
								'name' => 'column_5',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '5',
										),
									),
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '6',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'table',
								'sub_fields' => array(
									array(
										'key' => 'field_5adf727d1f5e1',
										'label' => 'Options',
										'name' => 'options',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'menu' => 'Menu',
											'content' => 'Content',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5adf727d1f5e2',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf727d1f5e1',
													'operator' => '==',
													'value' => 'content',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5adf727d1f5e3',
										'label' => 'Menu Location',
										'name' => 'menu',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf727d1f5e1',
													'operator' => '==',
													'value' => 'menu',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'sfooter-menu-1' => 'Super Footer Menu 1',
											'sfooter-menu-2' => 'Super Footer Menu 2',
											'sfooter-menu-3' => 'Super Footer Menu 3',
											'sfooter-menu-4' => 'Super Footer Menu 4',
											'sfooter-menu-5' => 'Super Footer Menu 5',
											'sfooter-menu-6' => 'Super Footer Menu 6',
										),
										'default_value' => array(
											0 => 'sfooter-menu-5',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
								),
							),
							array(
								'key' => 'field_5adf72a4006ff',
								'label' => 'Column 6',
								'name' => 'column_6',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5adf4de825059',
											'operator' => '==',
											'value' => '6',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'table',
								'sub_fields' => array(
									array(
										'key' => 'field_5adf72a400700',
										'label' => 'Options',
										'name' => 'options',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'menu' => 'Menu',
											'content' => 'Content',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5adf72a400701',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf72a400700',
													'operator' => '==',
													'value' => 'content',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5adf72a400702',
										'label' => 'Menu Location',
										'name' => 'menu',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5adf72a400700',
													'operator' => '==',
													'value' => 'menu',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'sfooter-menu-1' => 'Super Footer Menu 1',
											'sfooter-menu-2' => 'Super Footer Menu 2',
											'sfooter-menu-3' => 'Super Footer Menu 3',
											'sfooter-menu-4' => 'Super Footer Menu 4',
											'sfooter-menu-5' => 'Super Footer Menu 5',
											'sfooter-menu-6' => 'Super Footer Menu 6',
										),
										'default_value' => array(
											0 => 'sfooter-menu-6',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'ajax' => 0,
										'return_format' => 'value',
										'placeholder' => '',
									),
								),
							),
						),
					),
					array(
						'key' => 'field_5ad519884a515',
						'label' => 'Super Footer Top (Optional)',
						'name' => 'super_footer_top',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ad51818988ad',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5ad519634a514',
						'label' => 'Super Footer Bottom (Optional)',
						'name' => 'super_footer_bottom',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ad51818988ad',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5ad51818988dc',
						'label' => 'Dynamic Copyright Year',
						'name' => 'dynamic_copyright_year',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5ad519af4a516',
						'label' => 'Copyright Message',
						'name' => 'copyright_message',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ada4a8816266',
						'label' => 'Disclaimer',
						'name' => 'disclaimer',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ad5181898906',
						'label' => 'innermost Branding in Copyright',
						'name' => 'radii_branding_in_copyright',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 3,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	//social share
	acf_add_local_field_group(array(
		'key' => 'group_6266b89b6ce80',
		'title' => 'Social Share',
		'fields' => array(
			array(
				'key' => 'field_6266ba9ca6d25',
				'label' => '',
				'name' => 'social_share',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_6266b9349f7b1',
						'label' => 'Share Tag',
						'name' => 'share_tag',
						'type' => 'text',
						'instructions' => 'Enter a tag to enable social share sidebar.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6266bbc0f5d20',
						'label' => 'META OG Image',
						'name' => 'facebook_image',
						'type' => 'image',
						'instructions' => 'Dimension: 1200x630, File size: <1MB',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_6266bbf2f5d21',
						'label' => 'META Twitter Image',
						'name' => 'twitter_image',
						'type' => 'image',
						'instructions' => 'Optional. Dimension: 1200x630, File size: <1MB',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_6266bc2778b8a',
						'label' => 'Facebook App ID',
						'name' => 'facebook_app_id',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '20',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 4,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
	
	// Theme Options - Social Media
	acf_add_local_field_group(array(
		'key' => 'group_5ad51b3c2b025',
		'title' => 'Social Media Settings',
		'fields' => array(
			array(
				'key' => 'field_5ad51b3c3078a',
				'label' => '',
				'name' => 'social_media_settings',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5ad51b3c330fd',
						'label' => 'Display Social Media',
						'name' => 'display_social_media',
						'type' => 'checkbox',
						'instructions' => '*<a href="#acf-group_5ad518189015a">Super Footer</a> must be enabled.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'header' => 'Header',
							'superfooter' => 'Super Footer*',
							'bottomfooter' => 'Bottom Footer',
						),
						'allow_custom' => 0,
						'save_custom' => 0,
						'default_value' => array(
						),
						'layout' => 'horizontal',
						'toggle' => 0,
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5ad51b3c330fe',
						'label' => 'Border Style',
						'name' => 'social_media_border',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'' => 'None',
							'border-circle' => 'Circle',
							'border-square' => 'Square',
							'border-diamond' => 'Diamond',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ad51b7da231a',
						'label' => 'Social Media Links',
						'name' => 'social_media_links',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'row',
						'sub_fields' => array(
							array(
								'key' => 'field_5ad51baca231b',
								'label' => 'YouTube link',
								'name' => 'youtube_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ad51baca231v',
								'label' => 'Vimeo link',
								'name' => 'vimeo_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ad51c8b32ecf',
								'label' => 'Facebook link',
								'name' => 'facebook_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ad51c9332ed0',
								'label' => 'Twitter Link',
								'name' => 'twitter_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ad51c9d32ed1',
								'label' => 'LinkedIn Link',
								'name' => 'linkedin_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ad51cb932ed2',
								'label' => 'Instagram Link',
								'name' => 'instagram_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ad51cb932red',
								'label' => 'Reddit',
								'name' => 'reddit_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ad51cb932tik',
								'label' => 'Tik Tok Link',
								'name' => 'tiktok_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5bbe15b9767a7',
								'label' => 'Pinterest Link',
								'name' => 'pinterest_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5bbe15b976flk',
								'label' => 'Flickr Link',
								'name' => 'flickr_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5bbe15b9767a8',
								'label' => 'TripAdvisor Link',
								'name' => 'tripadvisor_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ad794c2ea6en',
								'label' => 'Ebay Link',
								'name' => 'ebay_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ad51cc132ed3',
								'label' => 'News / Subscribe Link',
								'name' => 'news_subscribe_link',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	// Theme Options - 404 config
	acf_add_local_field_group(array(
		'key' => 'group_5ad51d7e5f6c3',
		'title' => '404 Settings',
		'fields' => array(
			array(
				'key' => 'field_5ad51d7e655ad',
				'label' => '',
				'name' => '404_settings',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5ad51d7e67f00',
						'label' => 'Error 404 Page Title',
						'name' => 'error_404_page_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '404 - Not Found',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ad51da0f2d90',
						'label' => 'Error 404 Page Message',
						'name' => 'error_404_page_message',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Oops, This Page Could Not Be Found!',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5ae363dd40fae',
						'label' => 'Error 404 Banner Image',
						'name' => 'error_404_banner_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 6,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	// Backend Feature - Home Ribbon Alert
	acf_add_local_field_group(array(
		'key' => 'group_5bae8e0311e94',
		'title' => 'Home Ribbon Alert Options',
		'fields' => array(
			array(
				'key' => 'field_5bae8e2f901d9',
				'label' => '',
				'name' => 'home_banner_alert_options',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5bae8e55901da',
						'label' => 'Display',
						'name' => 'display',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => 'On',
						'ui_off_text' => 'Off',
					),
					array(
						'key' => 'field_5bae8e91901db',
						'label' => 'Title',
						'name' => 'text',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5bae8fe0901dc',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
					array(
						'key' => 'field_5bae8fe0901dd',
						'label' => 'Modal Content',
						'name' => 'content',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'home-alert',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	// Page Feature - Home Video Banner
	acf_add_local_field_group(array(
		'key' => 'group_5b56123673fe7',
		'title' => 'Video Banner',
		'fields' => array(
			array(
				'key' => 'field_5b5626fa67472',
				'label' => '',
				'name' => 'vid_intro_banner',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5b56278067473',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Enter introduction title',
						'prepend' => '',
						'append' => '',
						'maxlength' => 100,
					),
					array(
						'key' => 'field_5b5627ec67474',
						'label' => 'Tagline',
						'name' => 'tagline',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Enter introduction tagline',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5b56283067475',
						'label' => 'Desktop Video',
						'name' => 'video',
						'type' => 'url',
						'instructions' => 'Only support Vimeo or server hosted videos.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Enter introduction video url',
					),
					array(
						'key' => 'field_5b5628306747m',
						'label' => 'Mobile Video',
						'name' => 'mobile_video',
						'type' => 'url',
						'instructions' => 'Only support Vimeo or server hosted videos.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Optional mobile video url',
					),
					array(
						'key' => 'field_5b56285e67476',
						'label' => 'Fallback Background Image',
						'name' => 'desktop_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5ba3e4573f816',
						'label' => 'Mobile Banner Image',
						'name' => 'mobile_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

}

if (function_exists('get_field')) {
	// remove the html filter on all ACF fields
	add_filter('acf/allow_unfiltered_html', 'acfAllowAllFields');
	function acfAllowAllFields() {
	    return true;
	};
};

?>